### ISSUE TITLE
Reference documentation refers to spring-data-rest-hal-browser which no longer exists

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-data-rest#2002] opened 2021-04-21 19:26 UTC
The [Tools section](https://docs.spring.io/spring-data/rest/docs/3.5.0/reference/html/#tools) of the reference documentation refers to `spring-data-rest-hal-browser` which no longer exists.

**Comment by mp911de** [comment] 2021-04-26 14:53
Closing as duplicate of #2004

**Closed by mp911de** 2021-04-26 14:53 UTC
Labels: status: duplicate
